# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wojtek2kdev 
email: 
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wojtek2kdev.pl" # the base hostname & protocol for your site
github_username: wojtek2kdev 
# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/page/:num"
categories_names:
  "node-js": "Node JS"
  "sieci": "Sieci komputerowe"
  "iot": "Internet of Things"
  "narzedzia": "Narzedzia"
  "testy": "Testowanie aplikacji"
  "bazy-danych": "Bazy danych"
  "git": "Git"
  "rozne": "Rozne"
  "projekty": "Projekty"
  "poradniki": "Poradniki"
plugins:
  - jekyll-paginate
